name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: whoami
      run: whoami
    - name: environment
      run: env
    - name: process list
      run: ps -ef
    - name: whats in bin
      run: ls -al /bin
    - name: whats in proc
      run: ls -al /proc
    - name: do I have nc
      run: which nc
